<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\Seed\Courses.json" />
    <None Remove="Data\Seed\Educations.json" />
    <None Remove="Data\Seed\IndustryTypes.json" />
    <None Remove="Data\Seed\Jobs-Batch1.json" />
    <None Remove="Data\Seed\Jobs\Batch-2.json" />
    <None Remove="Data\Seed\Jobs\TextFile1.txt" />
    <None Remove="Data\Seed\Skills.json" />
    <None Remove="Data\Seed\Universities.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Seed\Courses.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Educations.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\IndustryTypes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\Batch-2.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\Jobs-Batch1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\Java.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\Python-AI.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\Node.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Jobs\TextFile1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Skills.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Seed\Universities.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.11.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />

    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.11" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">

      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="Resend" Version="0.5.1" />
   
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalHiringPlatform.Domain\LocalHiringPlatform.Domain.csproj" />
    <ProjectReference Include="..\LocalHiringPlatform.ServiceBus\LocalHiringPlatform.ServiceBus.csproj" />
  </ItemGroup>

</Project>
