# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Worker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build LocalHiringPlatform.Worker/LocalHiringPlatform.Worker.csproj --configuration Release

      - name: Clean publish folder
        shell: pwsh
        run: |
          Remove-Item "${{ env.DOTNET_ROOT }}/worker" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Publish
        run: dotnet publish LocalHiringPlatform.Worker/LocalHiringPlatform.Worker.csproj --configuration Release --no-build --output "${{env.DOTNET_ROOT}}/worker"
        
      - name: Prepare WebJob package
        shell: pwsh
        run: |
          $publish = "${{ env.DOTNET_ROOT }}/worker"

          $jobPath = Join-Path $publish "App_Data/jobs/continuous/LocalHireWorker"

          New-Item -ItemType Directory -Force -Path $jobPath | Out-Null

          Get-ChildItem $publish -Exclude "App_Data" | ForEach-Object {
              Copy-Item $_.FullName $jobPath -Recurse -Force
          }

          "LocalHiringPlatform.Worker.exe" | Out-File "$jobPath/run.cmd" -Encoding ascii

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: worker-app
          path: ${{ env.DOTNET_ROOT }}/worker

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: worker-app

      - name: Show downloaded files
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73B2A85909864D94902F40DC091B91E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD965DA1F1FB41D3BE33E945F34DA9D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_388AE11D79F548D18015BBE624050E2A }}

      - name: Deploy Worker
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'localhire-worker'
          slot-name: 'Production'
          package: .
          